### PR TITLE
Model updates, template tag with modal and translation guidelines

### PR DESCRIPTION
**Pull request by adibo**
- model extended to include 'info' field to be used as a communication channel to users upon new T&C; migration included
- translation guidelines added to readme (assuming: modeltranslation is used to do the actual translations)
- a template tag with css/js added to enable modal pop-up notification about the new terms (instead of immediate redirecting; just another means of using termsandconditions)
- base tests added
- small cleanups

### CODE REVIEW

**Comment by tlwhit2** [comment]
Looks very cool!  Before I merge this, is there any chance you can add a test for the templatetag? Cheers!

**Comment by adibo** [comment]
Base templatetags added.
Plus cleanup of tests directory (removed).

Cheers!

**Comment by cyface** [comment]
Thank you!!!!

**Comment by adibo** [comment]
My pleasure. :)
Happy to contribute.
I'd love to see the release on pip soon.

**Comment by cyface** [comment]
PyPi Release is up!

**Pull request merged**
