### PR TITLE
Compatibility with django 2

### PR DESCRIPTION
**Pull request by arthru**
This pull request proposes to upgrade code to support django 2.

This may break things for django < 2. I plan to make these changes compatible with Django 1.11 but I won't do anything for earlier versions...

### CODE REVIEW

**Comment by arthru** [comment]
I can't manage to exclude Python2/Django2 jobs from travis. These won't be successfull anyway as Django 2 dropped support for Python 2. I would be grateful for help in making this change...

**Comment by arthru** [comment]
Finally made travis success !

**Comment by cyface** [comment]
Hi! Thanks for submitting this!  It looks like you dropped support for Django 1.8 with this - is that a requirement, or can we try it with 1.8 and see if the tests pass in Travis?

**Comment by cyface** [comment]
Hi - I worked most of your changes in, and added conditionals for older versions of Django.  Thanks for your PR!

**Comment by arthru** [comment]
Sorry I've been sick since I created this PR and could not finish it...

Thanks for your work !

**Pull request closed without merging**
